// Generated by scripts/generate-api-client.mjs from public/api-contract.json.
export const endpoints = {
  "listResources": {
    "path": "/api/resources",
    "method": "GET"
  },
  "createResource": {
    "path": "/api/resources",
    "method": "POST"
  },
  "updateResource": {
    "path": "/api/resources/{id}",
    "method": "PATCH"
  },
  "deleteResource": {
    "path": "/api/resources/{id}",
    "method": "DELETE"
  },
  "getMissionData": {
    "path": "/api/data",
    "method": "GET"
  },
  "submitDailyResponse": {
    "path": "/api/responses",
    "method": "POST"
  }
} as const;
