import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export const db=()=>{if(!env.DB)throw new Error('Storage unavailable');return env.DB};
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export const today=()=>new Date().toISOString().slice(0,10);
export async function digest(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function passwordHash(pass:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export function same(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
export async function adminSession(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)mp_admin=([^;]+)/)?.[1];if(!token)return null;return await db().prepare('SELECT user_id FROM admin_sessions WHERE hash=? AND expires>?').bind(await digest(token),Date.now()).first<{user_id:string}>()}
export async function identity(req:Request){const signed=await getChatGPTUser();const session=await adminSession(req);let id=signed?.userId||session?.user_id;if(!id)throw new ApiError(401,'Sign in to access your workspace.');if(signed){await db().batch([db().prepare('INSERT INTO users (id,name,email,created_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email').bind(signed.userId,signed.displayName,signed.email,new Date().toISOString()),db().prepare('INSERT OR IGNORE INTO admin (key,user_id) VALUES (1,?)').bind(signed.userId)]);}const me=await db().prepare('SELECT * FROM users WHERE id=?').bind(id).first<any>();const owner=await db().prepare('SELECT user_id,password_hash FROM admin WHERE key=1').first<any>();return {me,isAdmin:owner?.user_id===id,adminSession:session?.user_id===id,adminConfigured:!!owner?.password_hash}}
export async function requireAdmin(req:Request){const auth=await identity(req);if(!auth.isAdmin||!auth.adminSession)throw new ApiError(403,'Sign in to the administrator portal to make changes.');return auth}
export function mutation(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new ApiError(403,'This request must come from your workspace.');if(req.method!=='DELETE'&&!req.headers.get('content-type')?.startsWith('application/json'))throw new ApiError(415,'Send JSON data.')}
export async function route(fn:()=>Promise<Response>){try{return await fn()}catch(e){if(e instanceof ApiError)return Response.json({error:e.message},{status:e.status});if(e instanceof SyntaxError)return Response.json({error:'Invalid JSON.'},{status:400});console.error('Mission Possible API:',e);return Response.json({error:'We could not complete this request. Your input has been kept. Please try again.'},{status:503})}}
